title : Carl Boettiger
tagline: Theoretical ecology and evolution
author :
  name : Carl Boettiger
  email : cboettig@gmail.com

permalink: /:year/:month/:day/:title.html
redirects: yes
exclude: [ _posts/source/ ]

markdown: pandoc
pandoc:
   extensions: [smart, mathjax]

#markdown: redcarpet2
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
