
title: Lab Notebook 
tagline: Theoretical ecology and evolution
author:
  name: Carl Boettiger
  givenName: Carl
  familyName: Boettiger
  twitter: cboettig
  github: cboettig
  mendeley: carl-boettiger
url: http://carlboettiger.info
repo: https://github.com/cboettig/labnotebook # used in linking history

## Google Analytics key (in _includes/analytics.html)
analytics: UA-18401403-1 


## Markdown Parser (standard Jekyll argument, extended to special parser)
markdown: pandoc
pandoc:
  extensions: 
    - smart
    - mathjax
#    - template: 'assets/datauri_template.html'   # Use with 'self-contained' to avoid header text in body
#    - self-contained                             # Archive images in posts as URIs.  Very slow, for archiving only.  
#    - mathml                                     # Use mathml for equations (Archival, HTML5/XML valid syntax)


permalink: /:year/:month/:day/:title.html
exclude: [ _posts/source/, _posts/_private/, assets/figures]

redirects: yes     ## A flag to turn on the redirects plugin
pageviews: yes    ## toggle on sidebar pageviews 



